### ISSUE TITLE
Exclude font files from newline check

### ISSUE THREAD

**Issue by jobara** [fluid-project/fluid-lint-all#11]
## Is your feature request related to a problem?

At the moment font files are included in the `lintspaces.newlines` check. However, these are binary files that do not require this check. At the moment a user of fluid-lint-all needs to setup configuration in the .fluidlintallrc.json file to explicitly exclude all of these files in the project. 

For example:

```JSON
{
    "lintspaces": {
        "newlines": {
            "excludes": [
                "./src/**/*.eot",
                "./src/**/*.otf",
                "./src/**/*.woff",
                "./src/**/*.woff2"
            ]
        }
    }
}
```

## Describe the solution you'd like
These binary files, and other common ones should automatically be excluded from the `lintspaces.newlines` check.

**Comment by the-t-in-rtf** [comment]
I will address this in #31.
