### ISSUE TITLE
Newlines check returns errors for PDF and PPTX files

### ISSUE THREAD

**Issue by greatislander** [fluid-project/fluid-lint-all#25]
## Describe the bug

Some more files which are erroneously included in the `lintspaces.newlines` check: .docx and .pdf.

 ### To reproduce
1. Run the `lintspaces.newlines` check against a project which contains PDF or PPTX files (e.g. https://github.com/codelearncreate/c2lc-project-website/runs/1979991318?check_suite_focus=true)
2. See the test failure.

### Expected behavior
The newlines check should not include these file types.

## Additional context or notes

Is there any way we can more broadly check for appropriate text files to which this should be applied and exclude all else?

Related: #4, #11

**Comment by the-t-in-rtf** [comment]
I will address all of these in #31.
