### ISSUE TITLE
Linting of indentation in JSON5 files is inconsistent with what is permitted in code

### ISSUE THREAD

**Issue by amb26** [fluid-project/fluid-lint-all#26]
Kettle's test config files include JSON5 files with aligned comments such as https://github.com/fluid-project/kettle/blob/main/tests/configs/config6.json5

When updating to fluid-lint-all version 1.0.4 from 1.0.0 these are now reported as being in error, with the following report:

12:54:04.093:    - tests\configs\config6.json5:
12:54:04.095:      (2:-) Expected an indentation at 0 instead of at 1.
12:54:04.096:      (3:-) Expected an indentation at 0 instead of at 1.

This is inconsistent with the alignment rules which are expecting when such comments occur in code.

Also, this version of fluid-lint-all should not have been released with a patch version update which has any substantive difference in behaviour from 1.0.0 - it should most likely have been 1.1.0

**Comment by the-t-in-rtf** [comment]
I suspect we picked up a default setting change from a library.  I will add a test fixture that triggers the error and investigate further.
