### ISSUE TITLE
Array values do not override properly in sources

### ISSUE THREAD

**Issue by amb26** [fluid-project/fluid-lint-all#29]
When adding, for example, a sources entry which looks as follows:

````
    "sources": {
        "css": ["./thing.css"], 
````

the resulting value received by the linter still retains mouse droppings of the last two entries in the grade defaults, e.g. 

````
  includes: [ './thing.css', './src/**/*.css', 'tests/**/*.css' ],
````
This is unlikely to be what the user intended. There should be a mergePolicy applied here to displace the default values.

**Comment by greatislander** [comment]
Perhaps related to #21?

**Comment by amb26** [comment]
Yup, looks like the same cause

**Comment by the-t-in-rtf** [comment]
@amb26, I think we should chat a bit about this.  I proposed the same fix for #21 before I saw this. In that ticket, @greatislander is actually asking for the opposite, having user excludes added to the defaults.  Otherwise adding even one of your own excludes means that you have to add them all.

**Comment by the-t-in-rtf** [comment]
I think I have an approach, I'll convert it to a map internally and reuse "bang notation" for material to be excluded/removed.  That should balance the need to add material with the need to clobber defaults that don't work for everyone.

**Comment by amb26** [comment]
> I think I have an approach, I'll convert it to a map internally and reuse "bang notation" for material to be excluded/removed. That should balance the need to add material with the need to clobber defaults that don't work for everyone.

Could you explain how this would work in a little more detail? I couldn't easily follow from the new impl. Do you mean that includes will clobber all defaults, and that excludes will continue to work additively?
