### ISSUE TITLE
Exclude .DS_Store files from newline check

### ISSUE THREAD

**Issue by klown** [fluid-project/fluid-lint-all#30]
## Is your feature request related to a problem?
The `lintspaces.newlines` check will report problems for any local `.DS_Store` files.  Even if manually removed, macOS will
add a `.DS_Store` file if looking at the files/folders using the Finder.  This is problematic in terms of having to clear out `.DS_Store` files with some regularity.

## Describe the solution you'd like
The `.DS_Store` files should be ignored or excluded from the newlines check.

## Describe alternative solutions you've considered
Adding `.DS_Store` to `.eslintignore` does not work since it does not override the rules in `lintspaces.newlines`.  It's a good solution (if it worked) since the project I'm working on does not have a `.eslintignore` in the upstream repository.  There are no worries about pushing a file that only applies to the local workspace.

Adding a `lintspaces` block to `fluid-lintallrc.json` listing `.DS_Store` is another possible solution that does work, e.g.,

```
    "lintspaces": {
        "newlines": {
            "excludes": [
                ".DS_Store"
            ]
        }
    }
```

**Comment by the-t-in-rtf** [comment]
I will address this in #31

**Comment by the-t-in-rtf** [comment]
Or maybe not?  @klown, if you can try the dev release of `1.0.5-dev.20210201T163615Z.cff0a11.GH-3`, I suspect that this one is better to handle using a `.gitignore` rule.

**Comment by klown** [comment]
Maybe not indeed @the-t-in-rtf.

I tried the dev release you suggested (remembering to remove my copy of `.eslintignore`) and `npm run lint` reported no `.DS_Store` errors.

**Comment by the-t-in-rtf** [comment]
Great, I'll close this one out and will ping the chat when the full release is out that adds `.gitignore` support.
