### ISSUE TITLE
esllint.json check reports errors when sourceType is module

### ISSUE THREAD

**Issue by jobara** [fluid-project/fluid-lint-all#51]
## Describe the bug
When your code is a module, you need to set the `sourceType` to `module` in the [eslint's parser options](https://eslint.org/docs/2.0.0/user-guide/configuring#specifying-parser-options). However doing this causes the eslint.json check to report `(-1:1) 'use strict' is unnecessary inside of modules.` error for all checked json files.

I tried setting the following configuration in .fluidlintallrc.json but it didn't help. In the end I disabled the eslint.json check.

```json
    "eslint": {
        "json": {
            "options": {
                "overrideConfig": {
                    "rules": {
                        "strict": ["error", "never"]
                    }
                }
            }
        }
    }
```

### To reproduce
1. In `.eslintrc.json` set the `sourceType` `parserOption` to `module`
2. Run the linting, making sure to include json files in the checks  

### Expected behavior

The eslint.json check shouldn't check for strict mode when the code is declared a module.

**Comment by duhrer** [comment]
@jobara, I don't actually have any projects that are a model, if you have a branch/project I could check out for testing purposes, that would help me look into this.

**Comment by duhrer** [comment]
Justin and I discussed this, he couldn't remember why this was needed.  I'll close for now, we can always reopen if needed.
