### ISSUE TITLE
Disabling json5lint, mdjsonlint, 

### ISSUE THREAD

**Issue by jobara** [fluid-project/fluid-lint-all#9]
## Describe the bug

Disabling `json5lint`, `mdjsonlint`, or `stylelint` throws the error `Cannot read property 'includes' of undefined`.

The errors come from the related `runChecks` function related to 

```javascript
if (that.options.config.enabled && !checksToRun || checksToRun.includes(that.options.key)) {
```

### To reproduce
1. In .fluidlintallrc.json disable any or all of the above mentioned checks
2. Run `npm run lint`
3. Notice that an error is thrown.

### Expected behavior

The linting should skip the disabled checks.

### Desktop
 - OS: macOS 11
 - Node: 14.15.0

**Comment by the-t-in-rtf** [comment]
The checks needed parentheses, as in "the check must be enabled" AND "one of these two things must be true".  Fixing it up now.
